name: Vercel Production Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment settings
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build project
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
